### ISSUE TITLE
معرفی توسعه دهنده

### ISSUE THREAD

**Issue by saeedlava** [GFW-knocker/Segaro_Dream#5]
سلام و درود بابد زحمات شما عزیز. خواستم بدونم کسی از گروهای توسعه دهنده روی این پروژه کانفیگ ازمایشی زده است. لطفا معرفی کنید اگر ممکنه.

**Comment by GFW-knocker** [comment]
سلام. بخش های اساسی این پروژه هنوز تکمیل نشده
