### ISSUE TITLE
ایده

### ISSUE THREAD

**Issue by DooMaria** [GFW-knocker/Segaro_Dream#8]
سلام 
من یک ایده مفید برای طرح جدید دارم

سابکرایب یوزر:
به این معنی که یوزر ماهانه به جای مبالغ کذایی و خنده داری که الان برای پروکسی ها هست (‌از ۱۰۰ هزار تومان تا ۴۰۰-۵۰۰ هزارتومان ماهانه) مبلغ خیلی کم تری رو برای اشتراک پرداخت بکنه
برای مثال: ۳۰الی۹۰ هزار تومان برای ماهانه الی ۳ماهه

توییتر هم پست کردم https://twitter.com/12340_eth/status/1671339106259939329

**Comment by GFW-knocker** [comment]
سلام. ببینید عرضه و تقاضا قیمت رو تعیین میکنه. کاری که ما میکنیم برا vpn ساز راه درامد جایگزین ایجاد میکنیم نه اینکه دستوری قیمت تعیین کنیم.
